name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Apk
    runs-on: ubuntu-latest
    steps:
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Gradle Setup
      uses: gradle/gradle-build-action@v2
    - name: Gradle Build
      run: gradle assembleRelease
    - name: upload apk
      uses: actions/upload-artifact@v3
      with:
        name: myapk
        path: app/build/outputs/apk/release/*.apk
