name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Apk
    runs-on: ubuntu-latest
    steps:
    - name: set up JDK 17
      uses: actions/setup-java@main
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    
    - name: Gradle Setup
      run: chmod +x gradlew
    
    - name: Gradle Build
      run: ./gradle assembleRelease
    
    - name: upload apk
      uses: actions/upload-artifact@v3
      with:
        name: myapk
        path: app/build/outputs/apk/release/*.apk
